//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanBunCha
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class dangky
    {
        public int mataikhoan { get; set; }

        
        public string tentaikhoan { get; set; }

       
        public string tendangnhap { get; set; }

       
        public string password { get; set; }

        
        public string sodienthoai { get; set; }

    
        public string diachi { get; set; }

        public virtual dangnhap dangnhap { get; set; }
    }
}
