//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanBunCha
{
    using System;
    using System.Collections.Generic;
    
    public partial class khohang
    {
        public string makho { get; set; }
        public string manhanvien { get; set; }
        public string nhacungcap { get; set; }
        public string tennguyenlieu { get; set; }
        public Nullable<int> soluong { get; set; }
    
        public virtual nhanvien nhanvien { get; set; }
    }
}
