//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanBunCha
{
    using System;
    using System.Collections.Generic;
    
    public partial class thanhtoan
    {
        public string mathanhtoan { get; set; }
        public string madonhang { get; set; }
        public Nullable<System.DateTime> ngaythanhtoan { get; set; }
        public string phuongthucthanhtoan { get; set; }
        public Nullable<decimal> sotien { get; set; }
    
        public virtual donhang donhang { get; set; }
    }
}
